name: flutter_json_layout
description: flutter_json_layout
version: 0.0.1
homepage: https://github.com/liyufengrex/flutter_json_layout

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.7
  auto_size_text: 3.0.0
  cached_network_image: ^3.2.3
  flutter_screenutil: 5.6.1
  smart_dart_json: ^0.0.1+1
  barcode_widget: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: