name: flutter_json_layout
description: flutter_json_layout
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.7
  auto_size_text: 3.0.0
  flutter_screenutil: 5.6.1
  pd_dart_json:
    git:
      url: ssh://git@gitlab.pin-dao.cn:222/pd_flutter/pd_dart_json.git
      ref: flutter_3.0
  barcode_widget: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: